project:
  type: website

website:
  title: "RDPS"
  navbar:
    left:
      - href: index.qmd
        text: Main
      # - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

